# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SekaiText(object):
    def setupUi(self, SekaiText):
        SekaiText.setObjectName("Sekai Test")
        SekaiText.resize(1024, 1024)

        self.centralwidget = QtWidgets.QWidget(SekaiText)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.tableWidgetSrc = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetSrc.setMinimumSize(QtCore.QSize(300, 500))
        self.tableWidgetSrc.setMaximumSize(QtCore.QSize(900, 16777215))
        self.tableWidgetSrc.setObjectName("tableWidgetSrc")
        self.tableWidgetSrc.setColumnCount(2)
        self.tableWidgetSrc.setRowCount(0)
        self.tableWidgetSrc.horizontalHeader().hide()
        self.tableWidgetSrc.horizontalHeader().resizeSection(0, 120)
        self.tableWidgetSrc.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        self.tableWidgetSrc.setIconSize(QtCore.QSize(48,48))
        self.gridLayout.addWidget(self.tableWidgetSrc, 0, 0, 1, 1)

        self.tableWidgetDst = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetDst.setMinimumSize(QtCore.QSize(300, 500))
        self.tableWidgetDst.setObjectName("tableWidgetDst")
        self.tableWidgetDst.setColumnCount(4)
        self.tableWidgetDst.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDst.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDst.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDst.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDst.setHorizontalHeaderItem(3, item)
        self.tableWidgetDst.horizontalHeader().resizeSection(0, 50)
        self.tableWidgetDst.horizontalHeader().resizeSection(1, 100)
        self.tableWidgetDst.horizontalHeader().resizeSection(2, 500)
        self.tableWidgetDst.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)
        self.tableWidgetDst.horizontalHeader().resizeSection(3, 100)
        self.tableWidgetDst.verticalHeader().hide()
        self.gridLayout.addWidget(self.tableWidgetDst, 0, 1, 1, 1)

        SekaiText.setCentralWidget(self.centralwidget)

        self.retranslateUi(SekaiText)
        QtCore.QMetaObject.connectSlotsByName(SekaiText)

    def retranslateUi(self, SekaiText):
        _translate = QtCore.QCoreApplication.translate
        SekaiText.setWindowTitle(_translate("SekaiTest", "Sekai Test"))
        item = self.tableWidgetDst.horizontalHeaderItem(0)
        item.setText(_translate("SekaiText", u"行号"))
        item = self.tableWidgetDst.horizontalHeaderItem(1)
        item.setText(_translate("SekaiText", u"说话人"))
        item = self.tableWidgetDst.horizontalHeaderItem(2)
        item.setText(_translate("SekaiText", u"内容文本"))
        item = self.tableWidgetDst.horizontalHeaderItem(3)
        item.setText(_translate("SekaiText", u"换行"))