# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_SekaiText(object):
    def setupUi(self, SekaiText):
        SekaiText.setObjectName("Sekai Judge")
        SekaiText.resize(1024, 1024)
        SekaiText.setMaximumSize(1800, 2048)

        self.centralwidget = QtWidgets.QWidget(SekaiText)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.profileLayout = QtWidgets.QVBoxLayout()
        self.topLayout = QtWidgets.QHBoxLayout()

        self.nameLable = QtWidgets.QLabel("昵称", self.centralwidget)
        self.nameLable.setFixedSize(QtCore.QSize(40, 30))
        self.topLayout.addWidget(self.nameLable)
        self.nameText = QtWidgets.QLineEdit(self.centralwidget)
        self.nameText.setFixedSize(QtCore.QSize(120, 30))
        self.topLayout.addWidget(self.nameText)

        self.blank = QtWidgets.QLabel("", self.centralwidget)
        self.blank.setFixedSize(QtCore.QSize(40, 30))
        self.topLayout.addWidget(self.blank)

        self.recommendLable = QtWidgets.QLabel("推的团或角色", self.centralwidget)
        self.recommendLable.setFixedSize(QtCore.QSize(110, 30))
        self.topLayout.addWidget(self.recommendLable)
        self.recommendText = QtWidgets.QLineEdit(self.centralwidget)
        self.recommendText.setFixedSize(QtCore.QSize(180, 30))
        self.topLayout.addWidget(self.recommendText)

        self.label = QtWidgets.QLabel("", self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(20, 30))
        self.label.setMaximumSize(QtCore.QSize(2000, 30))
        self.topLayout.addWidget(self.label)
        self.profileLayout.addLayout(self.topLayout)

        self.degreeLable = QtWidgets.QLabel("对游戏剧情的了解程度", self.centralwidget)
        self.degreeLable.setFixedSize(QtCore.QSize(410, 30))
        self.profileLayout.addWidget(self.degreeLable)
        self.degreeText = QtWidgets.QTextEdit(self.centralwidget)
        self.degreeText.setMinimumSize(QtCore.QSize(300, 30))
        self.degreeText.setMaximumSize(QtCore.QSize(900, 60))
        self.profileLayout.addWidget(self.degreeText)

        self.understandLable = QtWidgets.QLabel("对PJSK企划与VOCALOID的理解（选）", self.centralwidget)
        self.understandLable.setFixedSize(QtCore.QSize(410, 30))
        self.profileLayout.addWidget(self.understandLable)
        self.understandText = QtWidgets.QTextEdit(self.centralwidget)
        self.understandText.setMinimumSize(QtCore.QSize(300, 30))
        self.understandText.setMaximumSize(QtCore.QSize(900, 60))
        self.profileLayout.addWidget(self.understandText)

        self.Vblank = QtWidgets.QLabel("", self.centralwidget)
        self.Vblank.setFixedSize(QtCore.QSize(20, 20))
        self.profileLayout.addWidget(self.Vblank)

        self.gridLayout.addLayout(self.profileLayout, 0, 0, 1, 1)

        self.tableWidgetSrc = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetSrc.setMinimumSize(QtCore.QSize(300, 500))
        self.tableWidgetSrc.setMaximumSize(QtCore.QSize(900, 16777215))
        self.tableWidgetSrc.setObjectName("tableWidgetSrc")
        self.tableWidgetSrc.setColumnCount(2)
        self.tableWidgetSrc.setRowCount(0)
        self.tableWidgetSrc.horizontalHeader().hide()
        self.tableWidgetSrc.horizontalHeader().resizeSection(0, 120)
        self.tableWidgetSrc.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        self.tableWidgetSrc.setIconSize(QtCore.QSize(48,48))
        self.gridLayout.addWidget(self.tableWidgetSrc, 1, 0, 1, 1)

        self.tableWidgetDst = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetDst.setMinimumSize(QtCore.QSize(500, 500))
        self.tableWidgetDst.setObjectName("tableWidgetDst")
        self.tableWidgetDst.setColumnCount(4)
        self.tableWidgetDst.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDst.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDst.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDst.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDst.setHorizontalHeaderItem(3, item)
        self.tableWidgetDst.horizontalHeader().resizeSection(0, 50)
        self.tableWidgetDst.horizontalHeader().resizeSection(1, 100)
        self.tableWidgetDst.horizontalHeader().resizeSection(2, 500)
        self.tableWidgetDst.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.Stretch)
        self.tableWidgetDst.horizontalHeader().resizeSection(3, 100)
        self.tableWidgetDst.verticalHeader().hide()
        self.gridLayout.addWidget(self.tableWidgetDst, 0, 1, 2, 1)

        SekaiText.setCentralWidget(self.centralwidget)

        self.retranslateUi(SekaiText)
        QtCore.QMetaObject.connectSlotsByName(SekaiText)

    def retranslateUi(self, SekaiText):
        _translate = QtCore.QCoreApplication.translate
        SekaiText.setWindowTitle(_translate("SekaiTest", "Sekai Test"))
        item = self.tableWidgetDst.horizontalHeaderItem(0)
        item.setText(_translate("SekaiText", u"行号"))
        item = self.tableWidgetDst.horizontalHeaderItem(1)
        item.setText(_translate("SekaiText", u"说话人"))
        item = self.tableWidgetDst.horizontalHeaderItem(2)
        item.setText(_translate("SekaiText", u"内容文本"))
        item = self.tableWidgetDst.horizontalHeaderItem(3)
        item.setText(_translate("SekaiText", u"换行"))